# Generated by Django 5.2.8 on 2025-12-06 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(help_text="Display name shown to users. Can differ from Site.name (e.g., 'My Awesome App').", max_length=100)),
                ('tagline', models.CharField(blank=True, help_text="Short slogan or description (e.g., 'The best way to manage your tasks').", max_length=200)),
                ('theme', models.CharField(default='default', help_text='Theme identifier used for CSS styling. Maps to DaisyUI theme or custom CSS class.', max_length=50)),
                ('template_dir', models.CharField(blank=True, help_text="Template subdirectory name under templates/. If empty, defaults to first part of domain (e.g., 'mysite' for mysite.example.com). Templates here override defaults.", max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Site logo image. Recommended: SVG or PNG with transparent background, min 200px wide.', null=True, upload_to='sites/logos/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon. Recommended: 32x32 or 64x64 PNG, or ICO format.', null=True, upload_to='sites/favicons/')),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Primary brand color in hex format (e.g., #3B82F6). Used for buttons, links, accents.', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', help_text='Secondary brand color in hex format. Used for hover states, etc.', max_length=7)),
                ('meta_defaults', models.JSONField(blank=True, default=dict, help_text='<div class="site-help-box"><strong>SEO Meta Tags</strong><div class="purpose">Default meta tags applied to all pages. Individual pages can override these values.</div><ul class="keys-list"><li><code>title_suffix</code> - Appended to page titles</li><li><code>description</code> - Default meta description</li><li><code>og:image</code> - Default Open Graph image for social sharing</li><li><code>twitter:card</code> - Twitter card type: summary, summary_large_image</li><li><code>robots</code> - Search engine indexing: index/noindex, follow/nofollow</li></ul><pre>{\n  "title_suffix": " | My Site",\n  "description": "Your site description for search engines",\n  "og:image": "/static/images/og-default.jpg",\n  "twitter:card": "summary_large_image",\n  "robots": "index, follow"\n}</pre></div>')),
                ('head_scripts', models.JSONField(blank=True, default=list, help_text='<div class="site-help-box"><strong>Head Scripts & Styles</strong><div class="purpose">External scripts and stylesheets injected into &lt;head&gt;. Use for analytics, fonts, CSS.</div><ul class="keys-list"><li><code>type</code> - script (external JS), inline (inline JS), or link (CSS/preload)</li><li><code>src</code> - URL for external scripts</li><li><code>href</code> - URL for link tags (CSS, fonts)</li><li><code>content</code> - JavaScript code for inline scripts</li><li><code>async</code> - true/false - load script asynchronously</li><li><code>defer</code> - true/false - defer script execution</li></ul><pre>[\n  {"type": "script", "src": "https://www.googletagmanager.com/gtag/js?id=GA-XXX", "async": true},\n  {"type": "inline", "content": "window.dataLayer = window.dataLayer || [];"},\n  {"type": "link", "rel": "stylesheet", "href": "https://fonts.googleapis.com/css2?family=Inter"}\n]</pre></div>')),
                ('body_scripts', models.JSONField(blank=True, default=list, help_text='<div class="site-help-box"><strong>Body Scripts</strong><div class="purpose">Scripts injected at the end of &lt;body&gt;. Use for chat widgets, tracking pixels, etc.</div><pre>[\n  {"type": "script", "src": "https://widget.example.com/chat.js", "defer": true},\n  {"type": "inline", "content": "console.log(\'Page loaded\');"}\n]</pre></div>')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS styles for this site. Injected inline in &lt;head&gt;. Use for color overrides, custom fonts, or site-specific tweaks.')),
                ('default_language', models.CharField(default='en', help_text='Default language code (ISO 639-1). Examples: en, ro, fr, de, es.', max_length=10)),
                ('available_languages', models.JSONField(blank=True, default=list, help_text='<div class="site-help-box"><strong>Available Languages</strong><div class="purpose">List of language codes users can switch between. Leave empty for single-language sites.</div><pre>["en", "ro", "fr", "de"]</pre></div>')),
                ('timezone', models.CharField(default='UTC', help_text='Default timezone for this site. Examples: UTC, Europe/Bucharest, America/New_York.', max_length=50)),
                ('features', models.JSONField(blank=True, default=dict, help_text='<div class="site-help-box"><strong>Feature Flags</strong><div class="purpose">Toggle features on/off per site. Access in templates: {{ site_config.features.enable_blog }}</div><ul class="keys-list"><li><code>enable_*</code> - Enable/disable specific features</li><li><code>maintenance_mode</code> - Show maintenance page to non-staff users</li><li><code>beta_features</code> - Enable experimental features</li></ul><pre>{\n  "enable_blog": true,\n  "enable_shop": false,\n  "enable_comments": true,\n  "maintenance_mode": false,\n  "beta_features": false\n}</pre></div>')),
                ('integrations', models.JSONField(blank=True, default=dict, help_text='<div class="site-help-box"><strong>Third-Party Integrations</strong><div class="purpose">API keys and configs for external services. Use \'env:VAR_NAME\' for secrets (loaded from environment).</div><ul class="keys-list"><li><code>google_analytics.id</code> - GA4 measurement ID</li><li><code>stripe.public_key</code> - Stripe publishable key (safe to expose)</li><li><code>stripe.secret_key</code> - Use env:VAR_NAME for secrets!</li><li><code>sentry.dsn</code> - Sentry error tracking DSN</li></ul><pre>{\n  "google_analytics": {\n    "id": "G-XXXXXXXXXX",\n    "enabled": true\n  },\n  "stripe": {\n    "public_key": "pk_live_xxx",\n    "secret_key": "env:STRIPE_SECRET_KEY"\n  },\n  "sentry": {\n    "dsn": "env:SENTRY_DSN"\n  }\n}</pre></div>')),
                ('email_settings', models.JSONField(blank=True, default=dict, help_text='<div class="site-help-box"><strong>Email Configuration</strong><div class="purpose">Customize email sender details for this site. Overrides default Django email settings.</div><ul class="keys-list"><li><code>from_email</code> - Email address shown as sender</li><li><code>from_name</code> - Display name for sender</li><li><code>reply_to</code> - Reply-to address for user responses</li></ul><pre>{\n  "from_email": "noreply@mysite.com",\n  "from_name": "My Site",\n  "reply_to": "support@mysite.com"\n}</pre></div>')),
                ('auth_mode', models.CharField(choices=[('isolated', 'Isolated - Each domain has its own users'), ('shared', 'Shared - Cross-domain authentication via auth domain')], default='isolated', help_text='<strong>Isolated:</strong> Users are separate per domain. <strong>Shared:</strong> Single sign-on across domains via a central auth domain.', max_length=20)),
                ('is_auth_domain', models.BooleanField(default=False, help_text='Check this if this site is the central authentication provider. Other sites in shared mode will redirect here for login.')),
                ('social_auth_providers', models.JSONField(blank=True, default=list, help_text='<div class="site-help-box"><strong>Social Auth Providers</strong><div class="purpose">List of enabled OAuth providers. Must be configured in allauth settings.</div><pre>["google", "facebook", "github", "twitter"]</pre></div>')),
                ('auth_settings', models.JSONField(blank=True, default=dict, help_text='<div class="site-help-box"><strong>Authentication Settings</strong><div class="purpose">Fine-tune authentication behavior for this site.</div><ul class="keys-list"><li><code>allow_registration</code> - Allow new user signups (true/false)</li><li><code>require_email_verification</code> - Require email verification before login</li><li><code>login_redirect_url</code> - Where to redirect after successful login</li><li><code>logout_redirect_url</code> - Where to redirect after logout</li><li><code>session_cookie_age</code> - Session duration in seconds (1209600 = 2 weeks)</li></ul><pre>{\n  "allow_registration": true,\n  "require_email_verification": true,\n  "login_redirect_url": "/dashboard/",\n  "logout_redirect_url": "/",\n  "session_cookie_age": 1209600\n}</pre></div>')),
                ('extra_settings', models.JSONField(blank=True, default=dict, help_text='<div class="site-help-box"><strong>Extra Settings</strong><div class="purpose">Custom JSON settings for site-specific needs. Access via site_config.extra_settings in code.</div><pre>{\n  "custom_footer_text": "© 2025 My Company",\n  "support_email": "help@example.com",\n  "max_upload_size_mb": 10\n}</pre></div>')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive sites return 404. At least one site must remain active.')),
                ('is_primary', models.BooleanField(default=False, help_text='The primary/default site. Used when no domain matches. Only one site can be primary.')),
                ('path_prefix', models.CharField(blank=True, help_text="Development only: access this site via path prefix (e.g., '/mysite' for localhost:8000/mysite/). Leave empty for production domain-based routing.", max_length=50)),
                ('auth_domain', models.ForeignKey(blank=True, help_text='For shared auth mode: select the SiteProfile that handles login. Users will be redirected there to authenticate, then back with a JWT token.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authenticated_sites', to='site_management.siteprofile')),
                ('site', models.OneToOneField(help_text='The Django Site this profile extends. Each Site can have one profile.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profiles',
            },
        ),
    ]
