# Generated by Django 6.0 on 2025-12-14 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', help_text="User's role on this site. Admin has full access, Viewer is read-only.", max_length=20)),
                ('is_owner', models.BooleanField(default=False, help_text='If true, this user is the site owner and cannot be removed.')),
                ('site_profile', models.ForeignKey(help_text='The site this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='site_management.siteprofile')),
                ('user', models.ForeignKey(help_text='The user who has access to this site.', on_delete=django.db.models.deletion.CASCADE, related_name='site_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Member',
                'verbose_name_plural': 'Site Members',
                'ordering': ['-is_owner', 'role', 'user__email'],
                'unique_together': {('site_profile', 'user')},
            },
        ),
    ]
