# Generated by Django 6.0 on 2025-12-25 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_management', '0002_sitemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='extra_settings',
            field=models.JSONField(blank=True, default=dict, help_text='<div class="site-help-box"><strong>Extra Settings</strong><div class="purpose">Custom JSON settings including CORS/CSRF configuration. Access via site_config.extra_settings in code.</div><ul class="keys-list"><li><code>frontend_address</code> - Frontend/SPA URL for redirects and email links</li><li><code>cors_allowed_origins</code> - List of origins allowed to make cross-origin requests</li><li><code>csrf_trusted_origins</code> - List of origins trusted for CSRF validation</li><li><code>*</code> - Any custom key-value pairs for site-specific needs</li></ul><pre>{\n  "frontend_address": "https://app.example.com",\n  "cors_allowed_origins": ["https://app.example.com", "https://admin.example.com"],\n  "csrf_trusted_origins": ["https://app.example.com"],\n  "custom_footer_text": "© 2025 My Company",\n  "support_email": "help@example.com"\n}</pre></div>'),
        ),
        migrations.CreateModel(
            name='SiteAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_id', models.IntegerField(db_index=True, verbose_name='Site ID')),
                ('site_domain', models.CharField(max_length=255, verbose_name='Site Domain')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('member_add', 'Member Added'), ('member_remove', 'Member Removed'), ('member_update', 'Member Updated'), ('owner_transfer', 'Owner Transferred'), ('cache_invalidate', 'Cache Invalidated')], max_length=20, verbose_name='Action')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='User Email')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Changes')),
                ('previous_values', models.JSONField(blank=True, default=dict, verbose_name='Previous Values')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='New Values')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Site Audit Log',
                'verbose_name_plural': 'Site Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site_id', '-created_at'], name='site_manage_site_id_c8b43d_idx'), models.Index(fields=['user', '-created_at'], name='site_manage_user_id_03472a_idx'), models.Index(fields=['action', '-created_at'], name='site_manage_action_1fa316_idx')],
            },
        ),
    ]
