# Generated by Django 5.2.8 on 2025-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysettings',
            name='whitelist_paths',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of URL path prefixes that bypass security checks (e.g., /api/webhook/,/health/)', verbose_name='Whitelisted Paths'),
        ),
        migrations.AlterField(
            model_name='ipreputationconfig',
            name='provider',
            field=models.CharField(choices=[('abuseipdb', 'AbuseIPDB'), ('ipqualityscore', 'IPQualityScore'), ('custom', 'Custom API')], default='abuseipdb', help_text='IP reputation service provider', max_length=20, verbose_name='Provider'),
        ),
    ]
