# Generated by Django 6.0 on 2025-12-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_security', '0002_securitysettings_whitelist_paths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitysettings',
            name='whitelist_paths',
            field=models.TextField(blank=True, default='/api/webhook/,/stripe/webhook/,/health/,/healthz/', help_text='Comma-separated list of URL path prefixes that bypass security checks. Default: /api/webhook/, /stripe/webhook/, /health/, /healthz/', verbose_name='Whitelisted Paths'),
        ),
    ]
