# Generated by Django 6.0 on 2025-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_security', '0004_encrypt_firewall_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallconfig',
            name='_credentials',
            field=models.TextField(blank=True, db_column='credentials', default='', help_text='Provider-specific credentials (encrypted at rest)', verbose_name='Credentials'),
        ),
    ]
