# Generated by Django 6.0.5 on 2026-07-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_security', '0006_encrypt_ipreputation_api_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ipreputationcache',
            name='web_securit_ip_addr_c5461c_idx',
        ),
        migrations.RemoveIndex(
            model_name='ipthreatsummary',
            name='web_securit_ip_addr_c1a0d3_idx',
        ),
        migrations.AlterField(
            model_name='suspiciousrequest',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Threat category', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='suspiciousrequest',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Client IP address', verbose_name='IP Address'),
        ),
    ]
