# Generated by Django 6.0.5 on 2026-07-04 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_management', '0003_alter_siteprofile_extra_settings_siteauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='The testimonial content.')),
                ('author_name', models.CharField(help_text='Name of the person giving the testimonial.', max_length=100)),
                ('author_title', models.CharField(blank=True, help_text="Title or role (e.g., 'CEO at Company').", max_length=100)),
                ('author_photo', models.ImageField(blank=True, help_text='Photo of the testimonial author.', null=True, upload_to='testimonials/photos/')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1-5 stars.')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified customer testimonial.')),
                ('video_url', models.URLField(blank=True, help_text='URL to video testimonial (YouTube, Vimeo, etc.).')),
                ('proof_image', models.ImageField(blank=True, help_text='Screenshot or proof image.', null=True, upload_to='testimonials/proofs/')),
                ('schema_markup', models.JSONField(blank=True, default=dict, help_text='Auto-generated Schema.org Review markup.')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cms.category')),
                ('site', models.ForeignKey(blank=True, help_text='The site this category belongs to. Leave empty for all sites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_categories', to='site_management.siteprofile')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable landing pages for this site.')),
                ('cache_timeout', models.PositiveIntegerField(default=300, help_text='Cache timeout in seconds (default: 5 minutes).')),
                ('site', models.OneToOneField(help_text='The site these settings apply to.', on_delete=django.db.models.deletion.CASCADE, related_name='cms_settings', to='site_management.siteprofile')),
            ],
            options={
                'verbose_name': 'CMS Settings',
                'verbose_name_plural': 'CMS Settings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('site', models.ForeignKey(blank=True, help_text='The site this tag belongs to. Leave empty for all sites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_tags', to='site_management.siteprofile')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Internal title for this page.', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Must be unique per site (and unique among all-sites pages).', max_length=200)),
                ('page_type', models.CharField(choices=[('landing', 'Landing page'), ('content', 'Content page'), ('post', 'Blog post')], db_index=True, default='landing', help_text='Type of page: landing, content, or blog post.', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Publication date (used for blog post ordering and scheduling).', null=True)),
                ('excerpt', models.TextField(blank=True, default='', help_text='Short summary used in listings and SEO fallbacks.')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (max 70 chars). Defaults to title if empty.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (max 160 chars).', max_length=160)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if different from page URL.')),
                ('use_site_template', models.BooleanField(default=True, help_text="Use the site's base template. Uncheck for standalone pages.")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive pages return 404.')),
                ('form_disabled', models.BooleanField(default=False, help_text='Disable form submissions on this page.')),
                ('author', models.ForeignKey(blank=True, help_text='Author of this page (used for blog posts).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_pages', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Primary category for this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='cms.category')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cms_pages', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, help_text='The site this landing page belongs to. Leave empty to show on all sites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_pages', to='site_management.siteprofile')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this page.', related_name='pages', to='cms.tag')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_type', models.CharField(choices=[('hero_video', 'Hero with Video'), ('testimonial_single', 'Single Testimonial'), ('benefits_grid', 'Benefits Grid'), ('social_proof_cta', 'Social Proof CTA'), ('curriculum', 'Curriculum/Outline'), ('testimonials_grid', 'Testimonials Grid'), ('pricing', 'Pricing Section'), ('about_instructor', 'About Instructor'), ('guarantee', 'Guarantee Section'), ('faq', 'FAQ Section'), ('final_cta', 'Final CTA'), ('order_form', 'Order Form'), ('carousel', 'Carousel'), ('comparison', 'Comparison Slider'), ('gallery', 'Gallery'), ('jumbotron', 'Jumbotron'), ('qr_code', 'QR Code'), ('table', 'Table'), ('timeline', 'Timeline'), ('video', 'Video'), ('redirect', 'Redirect'), ('showcase', 'Showcase'), ('banner', 'Banner'), ('footer', 'Footer')], db_index=True, help_text='Type of zone determines the template used.', max_length=50)),
                ('title', models.CharField(blank=True, help_text='Short title for this zone (max 100 chars). Shown in admin listings for easy identification.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Help text and documentation for this zone. Describes expected content structure.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first).')),
                ('content', models.JSONField(blank=True, default=dict, help_text='Zone content (text, images, etc.) as JSON.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Zone configuration (styling, behavior) as JSON.')),
                ('template_name', models.CharField(blank=True, help_text='Custom template path. Must match "cms/zones/<name>.html". Leave empty for default.', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive zones are not rendered.')),
                ('page', models.ForeignKey(help_text='The landing page this zone belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='cms.page')),
                ('testimonial', models.ForeignKey(blank=True, help_text='Linked testimonial for testimonial zone types.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='cms.testimonial')),
            ],
            options={
                'verbose_name': 'Landing Page Zone',
                'verbose_name_plural': 'Landing Page Zones',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, help_text='Visitor email (validated and normalized).', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Visitor name.', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Visitor phone number.', max_length=50)),
                ('form_data', models.JSONField(default=dict, help_text='Sanitized form data as JSON.')),
                ('uploaded_files', models.JSONField(blank=True, default=list, help_text='Uploaded files as a list of storage paths (with field name and original filename).')),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('processed', 'Processed'), ('spam', 'Spam')], db_index=True, default='new', help_text='Triage status.', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP at submission time (proxy-aware).', null=True)),
                ('page', models.ForeignKey(help_text='Landing page that generated this submission.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cms.page')),
                ('zone', models.ForeignKey(blank=True, help_text='The ORDER_FORM zone that created this submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='cms.zone')),
            ],
            options={
                'verbose_name': 'Landing Page Submission',
                'verbose_name_plural': 'Landing Page Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Template name for easy identification.', max_length=100)),
                ('zone_type', models.CharField(choices=[('hero_video', 'Hero with Video'), ('testimonial_single', 'Single Testimonial'), ('benefits_grid', 'Benefits Grid'), ('social_proof_cta', 'Social Proof CTA'), ('curriculum', 'Curriculum/Outline'), ('testimonials_grid', 'Testimonials Grid'), ('pricing', 'Pricing Section'), ('about_instructor', 'About Instructor'), ('guarantee', 'Guarantee Section'), ('faq', 'FAQ Section'), ('final_cta', 'Final CTA'), ('order_form', 'Order Form'), ('carousel', 'Carousel'), ('comparison', 'Comparison Slider'), ('gallery', 'Gallery'), ('jumbotron', 'Jumbotron'), ('qr_code', 'QR Code'), ('table', 'Table'), ('timeline', 'Timeline'), ('video', 'Video'), ('redirect', 'Redirect'), ('showcase', 'Showcase'), ('banner', 'Banner'), ('footer', 'Footer')], db_index=True, help_text='Zone type this template applies to.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this template provides.')),
                ('default_content', models.JSONField(blank=True, default=dict, help_text='Default content JSON for this template.')),
                ('default_config', models.JSONField(blank=True, default=dict, help_text='Default configuration JSON for this template.')),
                ('template_file', models.CharField(blank=True, help_text='Custom template file path.', max_length=200)),
                ('preview_image', models.CharField(blank=True, default='', help_text='Static file path to preview image (e.g., images/cms/template-name.png).', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are not available for selection.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zone_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zone Template',
                'verbose_name_plural': 'Zone Templates',
                'ordering': ['zone_type', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='cms_category_unique_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('slug',), name='cms_category_unique_slug_all_sites'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='cms_tag_unique_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('slug',), name='cms_tag_unique_slug_all_sites'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='cms_unique_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('slug',), name='cms_unique_slug_all_sites'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='cms_submiss_status_b3e054_idx'),
        ),
    ]
